import "./globals.css";
import CursorEffectLayout from '../service/CursorEffectLayout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CursorEffectLayout>{children}</CursorEffectLayout>
      </body>
    </html>
  );
}
